### ISSUE TITLE
vite-plugin-vue-i18n  When some hi-in text will throw a build error

### ISSUE THREAD

**Issue by buzzlidwu** [intlify/bundle-tools#111]
### Reporting a bug?

this is my hi-in.json content, when I include the translation of the two keys AA_Alert_UsernameNotExist and AA_Alert_ValidationCode, it will cause a build error
```
{
  "Next": "अगला",
  "vcode": "प्रमाणीकरण कोड",
  "AA_Alert_UsernameNotExist": "दिया गया लॉग इन नाम हमारे सिस्टम में मौजूद नहीं है| कृपया एक मान्य लॉग इन नाम लिखें|",
  "AA_Alert_ValidationCode": "दिया गया सत्यापन कोड गलत है| कृपया एक सही सत्यापन कोड लिखें|"
}
```

```
[vite-plugin-vue-i18n] Cannot read properties of undefined (reading 'message')
file: D:/git-repo/components/src/pages/accountAssistance/locales/app.hi-in.json
TypeError: Cannot read properties of undefined (reading 'message')
    at Object.newOptions.onError (D:\git-repo\components\node_modules\@intlify\bundle-utils\lib\codegen.js:102:48)
    at Object.newOptions.onError (D:\git-repo\components\node_modules\@intlify\bundle-utils\lib\codegen.js:102:36)
    at newOptions.onError (D:\git-repo\components\node_modules\@intlify\bundle-utils\lib\codegen.js:102:36)
    at emitError (D:\git-repo\components\node_modules\@intlify\bundle-utils\node_modules\@intlify\message-compiler\dist\message-compiler.cjs.prod.js:822:13)    
    at parsePlural (D:\git-repo\components\node_modules\@intlify\bundle-utils\node_modules\@intlify\message-compiler\dist\message-compiler.cjs.prod.js:1044:13) 
    at parseResource (D:\git-repo\components\node_modules\@intlify\bundle-utils\node_modules\@intlify\message-compiler\dist\message-compiler.cjs.prod.js:1057:20)
    at Object.parse (D:\git-repo\components\node_modules\@intlify\bundle-utils\node_modules\@intlify\message-compiler\dist\message-compiler.cjs.prod.js:1067:21)
    at Object.baseCompile (D:\git-repo\componentss\node_modules\@intlify\bundle-utils\node_modules\@intlify\message-compiler\dist\message-compiler.cjs.prod.js:1375:24)
    at Object.generateMessageFunction (D:\git-repo\components\node_modules\@intlify\bundle-utils\lib\codegen.js:105:51)
    at Object.enterNode (D:\git-repo\components\node_modules\@intlify\bundle-utils\lib\json.js:104:61)

```

### Expected behavior

build successfully

### Reproduction

add these translations and build

```
  "AA_Alert_UsernameNotExist": "दिया गया लॉग इन नाम हमारे सिस्टम में मौजूद नहीं है| कृपया एक मान्य लॉग इन नाम लिखें|",
  "AA_Alert_ValidationCode": "दिया गया सत्यापन कोड गलत है| कृपया एक सही सत्यापन कोड लिखें|"
```

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 5.54 GB / 31.75 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.2 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.62)
    Internet Explorer: 11.0.22000.120
 npmPackages:
    @intlify/vite-plugin-vue-i18n: ^3.4.0 => 3.4.0 
    vite: ^2.9.6 => 2.9.6 
    vue: ^3.2.31 => 3.2.31 
    vue-i18n: ^9.2.0-beta.35 => 9.2.0-beta.35
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
Thank you for your feedbaback!

I'm not sure about hi-in text, but the text contains the pipeline character `|`.
In vue-i18n that character is a special character to handle in Pluralization.

If you want to use that character, you can use literal interpolation to work around it. 
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation

```json
{
  "Next": "अगला",
  "vcode": "प्रमाणीकरण कोड",
  "AA_Alert_UsernameNotExist": "दिया गया लॉग इन नाम हमारे सिस्टम में मौजूद नहीं है{'|'} कृपया एक मान्य लॉग इन नाम लिखें{'|'}",
  "AA_Alert_ValidationCode": "दिया गया सत्यापन कोड गलत है{'|'} कृपया एक सही सत्यापन कोड लिखें{'|'}"
}
```

**Comment by buzzlidwu** [comment]
thanks, I found the documentation and build it successfully. 
![image](https://user-images.githubusercontent.com/40494306/166487564-57c9174d-cb76-4ccf-a105-0f64f6dce797.png)
