### ISSUE TITLE
[vite] Internal server error: Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by N0153** [intlify/bundle-tools#148]
### Reporting a bug?

When starting the vite dev server, the process stops with the following message:
```
[vite] Internal server error: Cannot read properties of undefined (reading 'message')
  Plugin: vite-plugin-vue-i18n
  File: /home/projects/vite-plugin-vue-i18n-issue/src/i18n/locales/en.json
      at newOptions.onError (/home/projects/vite-plugin-vue-i18n-issue/node_modules/@intlify/bundle-utils/lib/codegen.js:102:48)
      at newOptions.onError (/home/projects/vite-plugin-vue-i18n-issue/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
      at newOptions.onError (/home/projects/vite-plugin-vue-i18n-issue/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
      at emitError (/home/projects/vite-plugin-vue-i18n-issue/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:197:13)
      at readTokenInPlaceholder (/home/projects/vite-plugin-vue-i18n-issue/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:646:21)
      at readToken (/home/projects/vite-plugin-vue-i18n-issue/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:776:20)
      at Object.nextToken (/home/projects/vite-plugin-vue-i18n-issue/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:823:16)
      at parseMessage (/home/projects/vite-plugin-vue-i18n-issue/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1029:50)
      at parseResource (/home/projects/vite-plugin-vue-i18n-issue/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1096:25)
      at Object.parse (/home/projects/vite-plugin-vue-i18n-issue/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1111:21)
```

The project is using both **vue-i18n** and **@intlify/vite-plugin-vue-i18n**. The messages for the default language are provided by an external JSON file, which includes a long value, with some escaped characters inside. 

For more details, please see the provided Stackblitz project.

### Expected behavior

Since both the json configuration file and the plugin configuration are valid, the project should be served correctly and the string should be successfully interpolated by the vue-i18n plugin.

### Reproduction

1. Run this Stackblitz project https://stackblitz.com/edit/vite-plugin-vue-i18n-issue?file=vite.config.json

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 5.15 GB / 15.90 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^5.0.0 => 5.0.0
    vite: ^3.0.1 => 3.0.1
    vue: ^3.2.37 => 3.2.37
    vue-i18n: ^9.1.10 => 9.1.10
```

### Screenshot

![image](https://user-images.githubusercontent.com/12370033/179481828-75816579-8ad8-4443-8cbd-ddddd3a7c206.png)

### Additional context

I tried editing the JSON configuration file, shortening the longest string and removing some escaped characters. It seems to be working after deleting enough characters, but I could not pinpoint the exact source of the issue.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by sunupdong** [comment]
I also encountered this problem, and the reason seems to be because of the `@` symbol

**Comment by kazupon** [comment]
Thank you for your reporting!
I've checked your repro codes!
I've found out there are special characters in your locale resources.
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters

you need to avoid special characters by using literal interpolation.
