### ISSUE TITLE
Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by aslero** [intlify/bundle-tools#164]
### Reporting a bug?

Cannot read properties of undefined (reading 'message')

### Expected behavior

Cannot read properties of undefined (reading 'message')

### Reproduction

I18n.ts

```
import { createI18n } from 'vue-i18n';
import messages from '@intlify/vite-plugin-vue-i18n/messages';

const i18n = createI18n({
  legacy: false,
  locale: 'en',
  messages
});

export default i18n;

```

vite.config.ts

```
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import vueI18n from '@intlify/vite-plugin-vue-i18n';
import eslint from 'vite-plugin-eslint';
import { resolve } from 'path';
import path from 'path'

export default defineConfig({
  plugins: [
    vue(),
    eslint({
      fix: true
    }),
    vueI18n({
      include: path.resolve(__dirname, './src/locales/**')
    })
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
      '@assets': resolve(__dirname, './src/assets'),
      '@layouts': resolve(__dirname, './src/layouts')
    }
  }
});

```

error

```
Cannot read properties of undefined (reading 'message')
12:26:54 PM [vite] Internal server error: Cannot read properties of undefined (reading 'message')
      at Object.newOptions.onError (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/bundle-utils/lib/codegen.js:102:48)
      at Object.newOptions.onError (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
      at newOptions.onError (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
      at emitError (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:866:13)
      at parsePlural (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1088:13)
      at parseResource (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1101:20)
      at Object.parse (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1111:21)
      at baseCompile (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1425:24)
      at generateMessageFunction (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/bundle-utils/lib/codegen.js:105:67)
      at Object.enterNode (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/bundle-utils/lib/json.js:110:89)
```

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
@intlify/vite-plugin-vue-i18n
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by oevery** [comment]
I also encountered this problem. After investigation, I found that it was caused by @ in the string.

**Comment by aslero** [comment]
> I also encountered this problem. After investigation, I found that it was caused by @ in the string.

on which line?

**Comment by dargmuesli** [comment]
There should be a matching error message, shouldn't it? Would you mind to reopen this ticket @kazupon / @aslero?
