### ISSUE TITLE
@intlify/vite-plugin-vue-i18n does not compatible with vite-ssg

### ISSUE THREAD

**Issue by ansidev** [intlify/bundle-tools#166]
### Reporting a bug?

@intlify/vite-plugin-vue-i18n does not compatible with vite-ssg.

More detailed information is described below.

### Expected behavior

Running `pnpm run build` will success.

### Reproduction

1. Clone https://github.com/ansidev/vitessg-vue-i18n-test
2. Run `pnpm install`
3. Run `pnpm run build`.

Actual output:

```
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
file:///.../vite3-i18n-test/.vite-ssg-temp/main.mjs:2
import { useI18n, createI18n } from "vue-i18n/dist/vue-i18n.runtime.esm-bundler.js";
                  ^^^^^^^^^^
SyntaxError: Named export 'createI18n' not found. The requested module 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js';
const { useI18n, createI18n } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async build (file:///.../vite3-i18n-test/node_modules/.pnpm/vite-ssg@0.20.2_xurzx7tuarc7mdzvuswetigddy/node_modules/vite-ssg/dist/chunks/build.mjs:171:87)
    at async Object.handler (file:///.../vite3-i18n-test/node_modules/.pnpm/vite-ssg@0.20.2_xurzx7tuarc7mdzvuswetigddy/node_modules/vite-ssg/dist/node/cli.mjs:20:3)
 ELIFECYCLE  Command failed with exit code 1.
```

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 26.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Brave Browser: 102.1.39.122
    Chrome: 104.0.5112.101
    Edge: 104.0.1293.63
    Firefox: 100.0
    Firefox Developer Edition: 104.0
    Safari: 15.6
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^6.0.1 => 6.0.1 
    vite: ^3.0.9 => 3.0.9 
    vue: ^3.2.37 => 3.2.37 
    vue-i18n: ^9.2.2 => 9.2.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by kazupon** [comment]
same issue
https://github.com/intlify/vue-i18n-next/issues/1131

**Comment by ansidev** [comment]
@kazupon Thank you! You can mark this issue as a duplicate issue of https://github.com/intlify/vue-i18n-next/issues/1131.

**Comment by kazupon** [comment]
I've just released vue-i18n@9.3.0-beta.1 and @intlify/vite-plugin-vue-i18n@7.0.0-beta.0
Please try to install and build with those!

Thanks!

**Comment by ansidev** [comment]
@kazupon I've tested these builds with the test repository, it seems to work.

**Comment by isgj** [comment]
Hi @kazupon , I was getting the same error here with the latest beta release `9.3.0-beta.12`, but I change the import to 

```diff
- import { createI18n } from 'vue-i18n';
+ import * as vuei18n from 'vue-i18n';
```

I get the following

```
(node:1946061) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/...../node_modules/vue-i18n/dist/vue-i18n.runtime.esm-bundler.js:1
export * from '../dist/vue-i18n.runtime.mjs'
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)

Node.js v18.12.1
```

Like the message says https://github.com/antoniandre/splitpanes/issues/176#issuecomment-1292695659
