### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'alias')

### ISSUE THREAD

**Issue by kazupon** [intlify/bundle-tools#197]
## Repro
- vite-vue-i18n-starter at `vite3-with-unplugin-vue-i18n` branch
https://github.com/intlify/vite-vue-i18n-starter/tree/vite3-with-unplugin-vue-i18n

## Step
`pnpm run build`

## What's happnening?
Occured in error:
```
error during build:
TypeError: Cannot read properties of undefined (reading 'alias')
    at config (file:///path/to/vite-vue-i18n-starter/node_modules/.pnpm/@intlify+unplugin-vue-i18n@0.7.1_vite@3.2.3+vue-i18n@9.3.0-beta.6/node_modules/@intlify/unplugin-vue-i18n/lib/index.mjs:142:38)
    at runConfigHook (file:///path/to/vite-vue-i18n-starter/node_modules/.pnpm/vite@3.2.3_@types+node@18.11.9/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:62865:31)
    at resolveConfig (file:///path/to/vite-vue-i18n-starter/node_modules/.pnpm/vite@3.2.3_@types+node@18.11.9/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:62374:20)
    at async doBuild (file:///path/to/vite-vue-i18n-starter/node_modules/.pnpm/vite@3.2.3_@types+node@18.11.9/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:45244:20)
    at async build (file:///path/to/vite-vue-i18n-starter/node_modules/.pnpm/vite@3.2.3_@types+node@18.11.9/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:45233:16)
    at async CAC.<anonymous> (file:///path/to/vite-vue-i18n-starter/node_modules/.pnpm/vite@3.2.3_@types+node@18.11.9/node_modules/vite/dist/node/cli.js:756:9)
```

**Comment by kazupon** [comment]
duplicate #194
