### ISSUE TITLE
Failing to set `include` param causes all json imports to be parsed by i18n

### ISSUE THREAD

**Issue by shadow-light** [intlify/bundle-tools#40]
### Reporting a bug?

I did not set the `include` config param since I don't use any translation files and just use <i18n> blocks.

This caused vite-plugin-vue-i18n to parse all json imports as message files. Such that a regular json import threw the error seen below:

```
file: .../app/src/app_config.json
error during build:
TypeError: Cannot read property 'message' of undefined
```

### Expected behavior

No files should be parsed for messages when `include` is not specified.

### Reproduction

Tell me if needed

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
System:
    OS: Linux 5.3 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 7.96 GB / 15.41 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 13.14.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Chrome: dev
  npmPackages:
    @intlify/vite-plugin-vue-i18n: ^2.4.0 => 2.4.0 
    @intlify/vue-i18n-loader: ^1.0.0 => 1.0.0 
    vite: ^2.4.4 => 2.4.4 
    vue: ^2.6.12 => 2.6.12 
    vue-i18n: ^9.1.7 => 9.1.7
```

### Additional context

```
[vite-plugin-vue-i18n] Cannot read property 'message' of undefined
file: .../app/src/app_config.json
error during build:
TypeError: Cannot read property 'message' of undefined
    at Object.newOptions.onError (.../app/node_modules/@intlify/bundle-utils/lib/codegen.js:102:48)
    at Object.newOptions.onError (.../app/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
    at newOptions.onError (.../app/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
    at emitError (.../app/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:174:13)
    at readTokenInLinked (.../app/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:728:21)
    at readToken (.../app/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:742:20)
    at Object.nextToken (.../app/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:784:16)
    at parseLinked (.../app/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:919:31)
    at parseMessage (.../app/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:1018:36)
    at parseResource (.../app/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:1057:25)
    at Object.parse (.../app/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:1072:21)
    at Object.baseCompile (.../app/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.prod.js:1380:24)
    at Object.generateMessageFunction (.../app/node_modules/@intlify/bundle-utils/lib/codegen.js:105:51)
    at Object.enterNode (.../app/node_modules/@intlify/bundle-utils/lib/json.js:96:61)
    at traverse (.../app/node_modules/jsonc-eslint-parser/lib/parser/traverse.js:45:13)
    at traverse (.../app/node_modules/jsonc-eslint-parser/lib/parser/traverse.js:49:13)

```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

**Comment by shadow-light** [comment]
Yes was trying to migrate to vite from webpack and later discovered v9 isn't compatible with Vue2. No worries, I assume it might be due to the version mismatch. Someone can reopen if they encounter it too.

**Comment by shadow-light** [comment]
@kazupon Is there any version of `vite-plugin-vue-i18n` that works with Vue 2?

I've got everything working except for i18n as messages are not loading from <i18n> blocks like they were in Webpack. I instead get missing key errors.
